#!/bin/sh

CW=$(date +%V)
CALWEEK='KW '$CW
STARTMONTH=$(date +%m)
STARTYEAR=$(date +%Y)



td=$(mktemp -d)

cd $td
colors="-s 0.8:0.0:0.0"

#2 Monate
 pcal -S -P a4 -m -F 1 -a de ${colors} $STARTMONTH $STARTYEAR 2 >c.ps

#2 Seiten query auf 1 Seite hoch
psnup -P a4 -2 c.ps  >c1.ps


cat <<EOF > empty.ps
%!PS-Adobe-2.0
%%CreationDate: 08 Oct 2013 (Tue) 09:15:11am
%%Creator: Generated by pcal v4.11.0 (http://pcal.sourceforge.net)
%%For: skainz
%%Routing: Simon Kainz
%%Title: calendar for 11/2013 - 12/2013
%%Pages: 2
%%PageOrder: Ascend
%%BoundingBox: 0 0 595 842
%%DocumentPaperSizes: A4
%%ProofMode: NotifyMe
%%EndComments

showpage

EOF


cat <<EOF >page1.ps
%!PS-Adobe-2.0
%%CreationDate: 08 Oct 2013 (Tue) 09:15:11am
%%Creator: Generated by pcal v4.11.0 (http://pcal.sourceforge.net)
%%For: skainz
%%Routing: Simon Kainz
%%Title: calendar for 11/2013 - 12/2013
%%Pages: 2
%%PageOrder: Ascend
%%BoundingBox: 0 0 595 842
%%DocumentPaperSizes: A4
%%ProofMode: NotifyMe
%%EndComments

/Times-Roman findfont
36 scalefont
setfont
newpath
420 750 moveto

(${CALWEEK}) show
showpage

EOF

psmerge -oalles.ps empty.ps c1.ps empty.ps empty.ps empty.ps page1.ps empty.ps empty.ps
psnup -p a4 -8 alles.ps

rm -rf $td
